# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/fih/fb0/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/fih/fb0/proprietary/libaudioalsa.so:/obj/lib/libaudioalsa.so 
       
# All the blobs necessary for fb0
PRODUCT_COPY_FILES += \
    vendor/fih/fb0/proprietary/qmuxd:/system/bin/qmuxd \
    vendor/fih/fb0/proprietary/hci_qcomm_init:/system/bin/hci_qcomm_init \
    vendor/fih/fb0/proprietary/geomagneticd:/system/bin/geomagneticd \
    vendor/fih/fb0/proprietary/orientationd:/system/bin/orientationd \
    vendor/fih/fb0/proprietary/proximityd:/system/bin/proximityd \
    vendor/fih/fb0/proprietary/lightd:/system/bin/lightd \
    vendor/fih/fb0/proprietary/nt_password_hash:/system/bin/nt_password_hash \
    vendor/fih/fb0/proprietary/hlr_auc_gw:/system/bin/hlr_auc_gw \
    vendor/fih/fb0/proprietary/hciattach:/system/bin/hciattach \
    vendor/fih/fb0/proprietary/hostapd:/system/bin/hostapd \
    vendor/fih/fb0/proprietary/hostapd_cli:/system/bin/hostapd_cli \
    vendor/fih/fb0/proprietary/netmgrd:/system/bin/netmgrd \
    vendor/fih/fb0/proprietary/rmt_storage:/system/bin/rmt_storage \
    vendor/fih/fb0/proprietary/port-bridge:/system/bin/port-bridge \
    vendor/fih/fb0/proprietary/btwlancoex:/system/bin/btwlancoex \
    vendor/fih/fb0/proprietary/libgemini.so:/system/lib/libgemini.so \
    vendor/fih/fb0/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/fih/fb0/proprietary/eglsubAndroid.so:/system/lib/egl/eglsubAndroid.so \
    vendor/fih/fb0/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/fih/fb0/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/fih/fb0/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/fih/fb0/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/fih/fb0/proprietary/libsc-a2xx.so:/system/lib/libsc-a2xx.so \
    vendor/fih/fb0/proprietary/libC2D2.so:/system/lib/libC2D2.so \
    vendor/fih/fb0/proprietary/libOpenVG.so:/system/lib/libOpenVG.so \
    vendor/fih/fb0/proprietary/sensors.fb0.so:/system/lib/hw/sensors.fb0.so \
    vendor/fih/fb0/proprietary/libcommondefs.so:/system/lib/libcommondefs.so \
    vendor/fih/fb0/proprietary/libgps.so:/system/lib/libgps.so \
    vendor/fih/fb0/proprietary/libloc_api-rpc-qc.so:/system/lib/libloc_api-rpc-qc.so \
    vendor/fih/fb0/proprietary/libloc_ext.so:/system/lib/libloc_ext.so \
    vendor/fih/fb0/proprietary/libloc-rpc.so:/system/lib/libloc-rpc.so \
    vendor/fih/fb0/proprietary/gps.fb0.so:/system/lib/hw/gps.fb0.so \
    vendor/fih/fb0/proprietary/libaudioalsa.so:/system/lib/libaudioalsa.so \
    vendor/fih/fb0/proprietary/rild:/system/bin/rild \
    vendor/fih/fb0/proprietary/libril.so:/system/lib/libril.so \
    vendor/fih/fb0/proprietary/libril-qc-1.so:/system/lib/libril-qc-1.so \
    vendor/fih/fb0/proprietary/libreference-ril.so:/system/lib/libreference-ril.so \
    vendor/fih/fb0/proprietary/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \
    vendor/fih/fb0/proprietary/libdiag.so:/system/lib/libdiag.so \
    vendor/fih/fb0/proprietary/liboncrpc.so:/system/lib/liboncrpc.so \
    vendor/fih/fb0/proprietary/libqmi.so:/system/lib/libqmi.so \
    vendor/fih/fb0/proprietary/libdsm.so:/system/lib/libdsm.so \
    vendor/fih/fb0/proprietary/libqueue.so:/system/lib/libqueue.so \
    vendor/fih/fb0/proprietary/libcm.so:/system/lib/libcm.so \
    vendor/fih/fb0/proprietary/libmmgsdilib.so:/system/lib/libmmgsdilib.so \
    vendor/fih/fb0/proprietary/libgsdi_exp.so:/system/lib/libgsdi_exp.so \
    vendor/fih/fb0/proprietary/libgstk_exp.so:/system/lib/libgstk_exp.so \
    vendor/fih/fb0/proprietary/libwms.so:/system/lib/libwms.so \
    vendor/fih/fb0/proprietary/libnv.so:/system/lib/libnv.so \
    vendor/fih/fb0/proprietary/libwmsts.so:/system/lib/libwmsts.so \
    vendor/fih/fb0/proprietary/libpbmlib.so:/system/lib/libpbmlib.so \
    vendor/fih/fb0/proprietary/libauth.so:/system/lib/libauth.so \
    vendor/fih/fb0/proprietary/libqdp.so:/system/lib/libqdp.so \
    vendor/fih/fb0/proprietary/libidl.so:/system/lib/libidl.so \
    vendor/fih/fb0/proprietary/libdsutils.so:/system/lib/libdsutils.so \
    vendor/fih/fb0/proprietary/liboem_rapi.so:/system/lib/liboem_rapi.so \
    vendor/fih/fb0/proprietary/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
    vendor/fih/fb0/proprietary/libnetmgr.so:/system/lib/libnetmgr.so \
    vendor/fih/fb0/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/fih/fb0/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/fih/fb0/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/fih/fb0/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/fih/fb0/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/fih/fb0/proprietary/camera.fb0.so:/system/lib/hw/camera.fb0.so

# Prebuilt libraries from CodeAurora
PRODUCT_COPY_FILES += \
    vendor/fih/fb0/proprietary/libv8.so:system/lib/libv8.so \
    vendor/fih/fb0/proprietary/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/fih/fb0/proprietary/libmmosal.so:system/lib/libmmosal.so \
    vendor/fih/fb0/proprietary/libmmparser.so:system/lib/libmmparser.so \
    vendor/fih/fb0/proprietary/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so

